import { inject } from '@adonisjs/core'
import logger from '@adonisjs/core/services/logger'
import env from '#start/env'
import { IStoryRepository } from '#stories/domain/repositories/story_repository'
import { IStoryGenerationService } from '#stories/domain/services/i_story_generation'
import { ITranslationService } from '#stories/domain/services/i_translation_service'
import { ChapterFactory } from '#stories/domain/factories/chapter_factory'
import { ImageUrl } from '#stories/domain/value-objects/media/image_url.vo'
import { Slug } from '#stories/domain/value-objects/metadata/slug.vo'
import { IUserRepository } from '#users/domain/repositories/user_repository'
import queue from '@rlanz/bull-queue/services/main'
import SendStoryGeneratedSuccessEmailJob from '#jobs/story/send_story_generated_success_email_job'
import type { Story } from '#stories/domain/entities/story.entity'
import type { StoryGenerated } from '#stories/domain/services/types/story_generated'

export interface GenerateStoryContentPayload {
  storyId: string
  synopsis: string
  theme: string
  protagonist: string
  childAge: number
  numberOfChapters: number
  language: string
  languageCode: string
  tone: string
  species: string
  appearancePreset?: string
  illustrationStyle?: string
  onProgress?: (progress: number) => Promise<void>
}

@inject()
export class GenerateStoryContentUseCase {
  private readonly SOURCE_LANGUAGE = env.get('STORY_SOURCE_LANGUAGE', 'French')
  private readonly SOURCE_LANGUAGE_CODE = env.get('STORY_SOURCE_LANGUAGE_CODE', 'FR')

  constructor(
    private readonly storyRepository: IStoryRepository,
    private readonly storyGenerationService: IStoryGenerationService,
    private readonly translationService: ITranslationService,
    private readonly userRepository: IUserRepository
  ) {}

  async execute(payload: GenerateStoryContentPayload) {
    logger.info(`🤖 Generating story content for: ${payload.storyId}`)

    // 1. Récupérer la story
    const story = await this.storyRepository.findById(payload.storyId)
    if (!story) throw new Error('Story not found')

    try {
      // 2. Déterminer si la traduction est nécessaire
      const needsTranslation = this.translationService.needsTranslation(payload.languageCode)
      const generationLanguage = needsTranslation ? this.SOURCE_LANGUAGE : payload.language

      if (needsTranslation) {
        logger.info(
          `🌐 Translation needed: generating in ${this.SOURCE_LANGUAGE}, will translate to ${payload.language} (${payload.languageCode})`
        )
      }

      // 3. Générer le contenu avec AI (en français si traduction nécessaire)
      let storyGenerated = await this.storyGenerationService.generateStory({
        storyId: payload.storyId,
        title: story.title,
        synopsis: payload.synopsis,
        theme: payload.theme,
        protagonist: payload.protagonist,
        childAge: payload.childAge,
        numberOfChapters: payload.numberOfChapters,
        language: generationLanguage,
        tone: payload.tone,
        species: payload.species,
        isPublic: story.isPublic(),
        ownerId: story.ownerId.getValue(),
        status: story.generationStatus,
        appearancePreset: payload.appearancePreset,
        illustrationStyle: payload.illustrationStyle,
        onProgress: payload.onProgress,
      })

      // 4. Traduire si nécessaire
      if (needsTranslation) {
        logger.info(`🔄 Translating story to ${payload.language}...`)
        storyGenerated = await this.translateStory(storyGenerated, payload.languageCode)
        await payload.onProgress?.(95)
        logger.info(`✅ Translation completed`)
      }

      // 5. Créer les entités Chapter
      const chapters = storyGenerated.chapters.map((chapterData) => {
        const position = chapterData.id.getValue()

        if (chapterData.image) {
          return ChapterFactory.createWithImage({
            position,
            title: chapterData.title,
            content: chapterData.content,
            imageUrl: chapterData.image.imageUrl.getValue(),
          })
        }

        return ChapterFactory.createWithoutImage({
          position,
          title: chapterData.title,
          content: chapterData.content,
        })
      })

      // 6. Mettre à jour la story avec le contenu généré
      // IMPORTANT: Utiliser le slug déjà généré et vérifié comme unique par le service de génération
      const updatedStory = story.completeGeneration(
        chapters,
        ImageUrl.create(storyGenerated.coverImageUrl),
        storyGenerated.conclusion,
        storyGenerated.title,
        Slug.create(storyGenerated.slug), // Use the unique slug generated by the story generation service
        storyGenerated.characterVisualLock // Persist character visual lock for image consistency
      )

      await this.storyRepository.save(updatedStory)

      // Dispatch success email (non-blocking)
      this.dispatchSuccessEmail(updatedStory).catch((error) => {
        logger.error('⚠️ Failed to dispatch success email job:', error.message)
      })

      logger.info(`✅ Story generation completed: ${payload.storyId}`)
      logger.info(`📖 Generated title: "${storyGenerated.title}"`)
      logger.info(`🔗 Generated slug: "${storyGenerated.slug}"`)

      return updatedStory
    } catch (error: any) {
      logger.error(`Story generation failed for ${payload.storyId}: ${error.message}`)
      // Ne PAS marquer comme failed ici - Bull Queue peut retenter ce job.
      // Le marquage et l'email se font dans GenerateStoryJob.rescue()
      // uniquement après épuisement des retries.
      throw error
    }
  }

  /**
   * Dispatch success email notification job
   */
  private async dispatchSuccessEmail(story: Story): Promise<void> {
    try {
      // Retrieve user information
      const user = await this.userRepository.findById(story.ownerId.getValue())

      if (!user) {
        logger.warn(`⚠️ User not found: ${story.ownerId.getValue()}`)
        return
      }

      // Dispatch email job
      await queue.dispatch(SendStoryGeneratedSuccessEmailJob, {
        recipientEmail: user.email.getValue(),
        recipientName: user.getFullName(),
        storyTitle: story.title,
        storySlug: story.slug.getValue(),
      })

      logger.info(`📧 Success email dispatched for ${user.email.getValue()}`)
    } catch (error: any) {
      logger.error('❌ Error dispatching success email:', error.message)
      // Don't throw - continue execution
    }
  }

  /**
   * Translate a generated story to the target language
   */
  private async translateStory(
    story: StoryGenerated,
    targetLanguageCode: string
  ): Promise<StoryGenerated> {
    // Translate title, synopsis, and conclusion in parallel
    const [titleResult, synopsisResult, conclusionResult] = await Promise.all([
      this.translationService.translate({
        text: story.title,
        sourceLanguage: this.SOURCE_LANGUAGE_CODE,
        targetLanguage: targetLanguageCode,
      }),
      this.translationService.translate({
        text: story.synopsis,
        sourceLanguage: this.SOURCE_LANGUAGE_CODE,
        targetLanguage: targetLanguageCode,
      }),
      this.translationService.translate({
        text: story.conclusion,
        sourceLanguage: this.SOURCE_LANGUAGE_CODE,
        targetLanguage: targetLanguageCode,
      }),
    ])

    // Translate chapters in parallel
    const translatedChapters = await Promise.all(
      story.chapters.map(async (chapter) => {
        const [chapterTitleResult, contentResult] = await Promise.all([
          this.translationService.translate({
            text: chapter.title,
            sourceLanguage: this.SOURCE_LANGUAGE_CODE,
            targetLanguage: targetLanguageCode,
          }),
          this.translationService.translate({
            text: chapter.content,
            sourceLanguage: this.SOURCE_LANGUAGE_CODE,
            targetLanguage: targetLanguageCode,
          }),
        ])

        return {
          ...chapter,
          title: chapterTitleResult.translatedText,
          content: contentResult.translatedText,
        }
      })
    )

    logger.info(`📊 Translation provider used: ${titleResult.provider}`)

    return {
      ...story,
      title: titleResult.translatedText,
      synopsis: synopsisResult.translatedText,
      conclusion: conclusionResult.translatedText,
      chapters: translatedChapters as StoryGenerated['chapters'],
    }
  }
}
