export const ALLOWED_LANGUAGES = {
  FR: 'French',
  EN: 'English',
  LI: 'Lingala',
  ES: 'Spanish',
  PT: 'Portuguese',
  DE: 'Deutsch',
  IT: 'Italiano',
  NL: 'Nederlands',
  PL: 'Polski',
  RU: 'Russian',
  TR: 'Turkish',
  AR: 'Arabic',
  JA: 'Japanese',
} as const;