/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessTokens {
  abilities: string;
  created_at: Timestamp;
  expires_at: Timestamp | null;
  hash: string;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  name: string;
  tokenable_id: string;
  type: string;
  updated_at: Timestamp;
}

export interface Characters {
  background_story: string | null;
  character_image: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  personality_traits: Json | null;
  physical_appearance: Json | null;
  role: string;
  story_id: string;
  updated_at: Generated<Timestamp>;
}

export interface EmailVerificationTokens {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: Generated<string>;
  token: string;
  user_id: string;
}

export interface Languages {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_free: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SocialAccounts {
  access_token: string;
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string | null;
  provider: string;
  provider_user_id: string;
  refresh_token: string | null;
  token_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Stories {
  appearance_preset: Generated<string | null>;
  chapter_images: Generated<Json | null>;
  chapters: number;
  character_visual_lock: string | null;
  child_age: Generated<number>;
  conclusion: Generated<string>;
  content: string;
  cover_image: string;
  created_at: Timestamp;
  generation_completed_at: Timestamp | null;
  generation_error: string | null;
  generation_started_at: Timestamp | null;
  generation_status: Generated<string>;
  id: Generated<string>;
  illustration_style: Generated<string | null>;
  job_id: string | null;
  language_id: string | null;
  protagonist: Generated<string>;
  public: Generated<boolean>;
  slug: string | null;
  species: Generated<string>;
  story_chapters: Generated<Json>;
  synopsis: string;
  theme_id: string | null;
  title: string;
  tone_id: string | null;
  updated_at: Timestamp;
  user_id: string;
}

export interface Subscriptions {
  created_at: Generated<Timestamp>;
  entitlement_id: string | null;
  expiration_date: Timestamp | null;
  grace_period_expires_date: Timestamp | null;
  id: Generated<string>;
  last_verified_at: Timestamp | null;
  last_webhook_event_id: string | null;
  management_url: string | null;
  original_purchase_date: Timestamp | null;
  product_id: string | null;
  revenuecat_app_user_id: string | null;
  status: Generated<string>;
  store: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  will_renew: Generated<boolean>;
}

export interface Themes {
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  key: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Tones {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Timestamp;
  customer_id: string | null;
  email: string;
  email_verified_at: Timestamp | null;
  firstname: string;
  id: Generated<string>;
  lastname: string;
  password: string | null;
  role: Generated<number>;
  updated_at: Timestamp;
}

export interface WebhookEvents {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  event_id: string;
  event_type: string;
  id: Generated<string>;
  payload: Json;
  processed_at: Timestamp | null;
  retry_count: Generated<number>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  access_tokens: AccessTokens;
  characters: Characters;
  email_verification_tokens: EmailVerificationTokens;
  languages: Languages;
  social_accounts: SocialAccounts;
  stories: Stories;
  subscriptions: Subscriptions;
  themes: Themes;
  tones: Tones;
  users: Users;
  webhook_events: WebhookEvents;
}
